name: 'OpenAPI Diff'
description: 'Generates diff between two OpenAPI spec.'
inputs:
  head-spec:
    description: 'The file path of the head spec.'
    required: true
  base-spec:
    description: 'The file path of the base spec.'
    required: true
  fail-on-incompatible:
    description: "If 'true', the action fails when there's more than zero incompatible changes."
    default: 'true'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base-spec }}
    - ${{ inputs.head-spec }}
    - ${{ inputs.fail-on-incompatible }}
